# Generated by Django 5.1.6 on 2025-09-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
            options={
                'db_table': 'imagenproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=100, unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion_producto', models.TextField()),
                ('valor_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('categoria_producto', models.CharField(choices=[('camisetas', 'Camisetas'), ('abrigos', 'Abrigos'), ('sacos', 'Sacos'), ('chaquetas', 'Chaquetas'), ('pantalones', 'Pantalones'), ('jeans', 'Jeans'), ('faldas', 'Faldas'), ('vestidos', 'Vestidos'), ('accesorios', 'Accesorios'), ('bolsos', 'Bolsos')], max_length=20)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('tallas_disponibles', models.CharField(max_length=100, null=True)),
                ('colores_disponibles', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proveedores', models.ManyToManyField(blank=True, db_table='proveedor_marca', to='core.proveedor')),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
    ]
